#!/usr/bin/env bash

echo "Running post checkout hook at '$(pwd)'"

# NB This runs in the same dir as the Dockerfile, hence any relative paths must be relative to the python_gpu Dockerfile
cp ../../../../python_minimal/python/jupyter/jupyter_additions.sh .
cp ../../../../python_minimal/python/jupyter/jupyter.conf .
cp ../../../../python_minimal/python/jupyter/run_jupyter.sh .