#!/usr/bin/env bash

echo "Running post checkout hook at '$(pwd)'"

# NB This runs in the same dir as the Dockerfile, hence any relative paths must be relative to the python_gpu Dockerfile
cp ../../python_minimal/python_additions.sh .